name: CSharp files styling

on: push

jobs:

  git-diff:

    name: Git diff
    runs-on: ubuntu-latest

    steps:

      - id: file_changes
        name: Detect changed file paths
        uses: trilom/file-changes-action@master
        runs-on: ubuntu-latest

  enforce-styling:

    name: Encorce styling
    runs-on: windows-latest

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Print changed file paths
        run: |
          echo 'Below shows a list of changed file paths'
          echo '${{ steps.file_changes.outputs.files}}'

      - name: Setup Visual Studio Command Prompt
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install dotnet format
        run: dotnet tool update --global dotnet-format

      - name: Format solution
        run: |
          dotnet-format