name: Format CSharp files check

on: push

jobs:
  format-sln:
    runs-on: windows-latest
    name: Solution format
    steps:
    - name: Clone .NET Samples
      uses: actions/checkout@v1
  
    - name: Setup Visual Studio Command Prompt
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Format solution
      run: |
        dotnet-format