name: CSharp files styling

on: push

jobs:

  enforce-styling:

    name: Encorce styling
    runs-on: windows-latest

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Visual Studio Command Prompt
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install dotnet format
        run: dotnet tool update --global dotnet-format

      - name: Format solution
        run: |
          dotnet-format --check